In [ ]:
#2 Write a function that takes a tuple of numbers and returns the smallest number in the tuple.
tuplenum = (1, 5, 7, 9, 3)
print(tuplenum)
print ("min value element : ", min(tuplenum))

(1, 5, 7, 9, 3)
min value element :  1

list=[1,2,8,9,45,28,30]
print("sum of number : " sumlist)

In [ ]:
# Q 1:
list=[1,2,8,9,45,28,30]
print(list)
#print(int(input("enter number in list: ",list)))
print("sum of number : ", sum(list))

[1, 2, 8, 9, 45, 28, 30]
sum of number :  123

In [5]:
# 3 Write a function that takes a set of numbers and returns a new set with each element squared
x=[1,2,3,4,5,6,7,8,9]
y=[]
for i in x:
   y.append(i*i)
print(y)

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [8]:
# Example dictionary
d = {"name": "shahina",
     "father name": "Siddiq",
     "group": 3}

# Convert dictionary keys to a list
keys_list = list(d.keys())

print(keys_list)

['name', 'father name', 'group']